[build]
  # No build command needed for static HTML site
  command = ""
  # Publish the root directory
  publish = "."
  
[build.environment]
  # Disable Node.js detection completely
  NODE_VERSION = ""
  NPM_FLAGS = ""
  NODE_ENV = "production"
  
# Redirect rules
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Only redirect 404 errors to index.html (for any missing pages)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
